# all actions require a metadata file that uses yml syntax
# the data in the metadata file defines the inputs, outputs and main entrypoint for your action
name: "Hello Actions"
description: "Greet someone"
author: "jackmama338@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"